### ISSUE TITLE
output copy & paste?

### ISSUE THREAD

**Issue by teuben** [chongchonghe/acap#1]
on my ubuntu the output is some low grade dithering, so i can't capture it with ccopy and paste into another app

**Comment by chongchonghe** [comment]
Selecting and copying texts on Tkinter GUI is a hard problem that I didn't manage to solve. Currently, it is not possible to copy texts on macOS or Linux. The workaround is to copy the outputs from the terminal. In the terminal where you start ACAP, it keeps records of all inputs and outputs (in cgs).

**Comment by teuben** [comment]
i see one answer:  the output is also in the terminal where the script was started from.

**Comment by chongchonghe** [comment]
Finally did it! Check the copypaste branch.

**Comment by teuben** [comment]
indeed, this worked, great job.    If you put your requirements in requirements.txt then users can simply pip install these dependencies from it. I didn't see the branch, it worked from master.

**Comment by chongchonghe** [comment]
I merged it to master. No need for requirements.txt in a more modern paradigm. It’s in setup.py. You should see something like “requirement already satisfied …” when doing pip install.
