### ISSUE TITLE
astropy examples

### ISSUE THREAD

**Issue by teuben** [chongchonghe/acap#2]
I tried out your examples in astropy, to see how they look different (maybe useful for your docs)

from astropy.constants import G, M_sun, au, k_B
import numpy as np
import astropy.units as u

# sqrt(G Msun / au)
np.sqrt(G*M_sun/au)
<Quantity 29784.69182968 m / s>

# 1 Mpc * 2 arcsec
(1*u.Mpc * 2*u.arcsec).decompose()
<Quantity 2.99195741e+17 m rad>

# h 2.4GHz / k_B' 
(h * 2.4*u.GHz / k_B).decompose()
<Quantity 0.11518183 K>

**Comment by chongchonghe** [comment]
The second one is indeed a mistake. Now I fixed it. The results of the second input now have the correct units 'm rad'. 

Do you see any difference in the first and thirds results?

**Comment by teuben** [comment]
no, i didn't even look carefully at all the digits, i should have.   my point is that this is a good example for the manual/readme file :-)
