### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by teuben** [chongchonghe/acap#3]
A possible enhancement is the use of setup.py
With a requirements.txt you give the dependencies.
No more need to explain installation symlinks etc.  it's all standard pip install or pip install -e

**Comment by chongchonghe** [comment]
Check the setup branch. This is the first time I do python packaging. Would you like to have a look at how well it goes and let me know? Thanks.

**Comment by teuben** [comment]
that looks like it's working. I tried both "pip install ." and "pip install -e ."  (my favorite) and the command is now installed in python's location. This also means virtualenv should work. I didn't test the python setup.py method, they are harder to manage the uninstall from.   Is this this is ready for merge.

Only one final comment, usually for real packages , the script would be hidden one level deeper, but I don't tihnk that's an issue here.

**Comment by chongchonghe** [comment]
I started with bin/acap, but then realized that will cause confusion to people who just want to run it with `python acap`, and there's only one python script anyway.
